select * from customer limit 20



-- Q1. Total revenue generated by male vs. female customers
select gender, sum(purchase_amount) as revenue
from customer
group by gender



-- Q2. Customers who used a discount but spent more than average
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes'  and purchase_amount >= (select avg(purchase_amount) from customer)



-- Q3. Top 5 products with highest average review rating

SELECT item_purchased,
       AVG(review_rating) AS average_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_product_rating DESC
LIMIT 5;

-- Q4. Compare average Purchase Amounts for Standard and Express Shipping
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;



-- Q5. Compare average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;



-- Q6. Top 5 products with highest percentage of purchases with discounts applied
SELECT item_purchased,
       100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;



-- Q7. Segment customers into New, Returning, and Loyal
with customer_type as (
select customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer
)

select customer_segment,count(*) as "Number of Customers" 
from customer_type 
group by customer_segment;


-- Q8. Top 3 most purchased products within each category
with item_counts as (
select category, 
item_purchased, 
COUNT(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select  category, item_purchased, total_orders
from item_counts
where item_rank <= 3;



-- Q9. Find repeat buyers (>5 previous purchases) by subscription status.
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status



-- Q10. Revenue contribution of each age group
SELECT 
    CASE 
        WHEN age_group <= 38 THEN 'Young Adult'
        WHEN age_group BETWEEN 39 AND 50 THEN 'Middle-aged'
        WHEN age_group BETWEEN 51 AND 65 THEN 'Adult'
        ELSE 'Senior' 
    END AS age_category,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_category
ORDER BY total_revenue DESC;





